### ISSUE TITLE
Webscraper requires update

### ISSUE THREAD

**Issue by sigurdurf** [sigurdurf/foodbot#1]
New version of the Málið website was deployed after the summer. Scraper needs an update to function properly

**Comment by SvartaHjarta** [comment]
Fæ ekkert þegar ég reyni að ná í síðuna með requests en fann [api](https://prod-10.westeurope.logic.azure.com/workflows/661a8f1211d34ed98db39ea8c6caa52f/triggers/manual/paths/invoke?api-version=2016-06-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=BpkZO2O35IlCXBbLQ7xzM75G0GWbx7D-enVq6I8b7F8)

svo við þurfum bara að requesta þetta og vinna með json :)

**Comment by SvartaHjarta** [comment]
> [{'day': 'Wednesday', 'main': 'Svínakjöt súrsætsósa og krydduð hrísgrjón.', 'vegan': 'Chilli sin carne með hrísgrjón. (V)', 'salat': '', 'soup': 'Grænmetis súpa. (V)'}]
